# Generated by Django 5.0.6 on 2024-07-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrearEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Evento')),
                ('nombre', models.TextField(verbose_name='Nombre del Evento')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('hora', models.TimeField(verbose_name='Hora del Evento')),
                ('lugar', models.TextField(verbose_name='Lugar del Evento')),
                ('tipo', models.TextField(verbose_name='Tipo de Evento')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Evento')),
            ],
            options={
                'verbose_name': 'Crear Evento',
                'verbose_name_plural': 'Crear Eventos',
                'ordering': ['fecha'],
            },
        ),
    ]
