# Generated by Django 5.0.6 on 2024-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michoacan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('evento', models.TextField(default='Eventos')),
                ('precio', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(default='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created'],
            },
        ),
    ]
